import Head from "next/head";
import React from "react";
import styles from "./about.module.css";

const index = () => {
  return (
    <>
      <Head>
        <title>ZET : Become a certified financial Advisior and Earn Big</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/unnamed.ico" />
      </Head>
      <div className={styles.aboutContainer}>
        <div className={styles.missionContainer}>
          <text className={styles.mission}>OUR MISSION</text>
          <div className={styles.innerText}>
            <text className={styles.innerText1}>
              Enabling financial inclusion for the next billion Indians
              <br /> & making their Zindagi Set. Building a platform that
              enables you to sell <br /> financial products & earn up to Rs. 1
              lakh every month.
            </text>
          </div>
          <div className={styles.innerText2}>
            <p className={styles.subText}>EARN BETTER. LIVE BETTER.</p>
          </div>
        </div>
      </div>
      <div className={styles.year}>
        <text className={styles.yearText}>How we evolved over the years</text>
        <div className={styles.yearImage}>
          <img
            src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FGrowth.abe5b7d8.png&w=3840&q=100"
            alt="image"
          />
        </div>
        
      </div>
      <hr className={styles.hrLine} />
      <div className={styles.gotFeatured}>
        <div className={styles.fTitle}>
          <p className={styles.featuredTitle}>Got Featured</p>
        </div>
        <div className={styles.fList}>
          <div className={styles.featuredLink}>
            <div className={styles.img1}>
              <a href="https://economictimes.indiatimes.com/tech/funding/onecode-has-raised-13-million-in-fresh-funding-led-by-general-catalyst/articleshow/90571172.cms">
                <img
                  src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FEconomicTimes.5724030e.png&w=1080&q=75"
                  alt="image"
                />
              </a>
            </div>
          </div>
          <div className={styles.featuredLink}>
            <div className={styles.img1}>
              <a href="https://inc42.com/buzz/fintech-startup-onecode-raises-13mn-in-series-a-round-led-by-general-catalyst/">
                <img
                  src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FInc42.7697aec8.png&w=1080&q=75"
                  alt="image"
                />
              </a>
            </div>
          </div>
          <div className={styles.featuredLink}>
            <div className={styles.img1}>
              <a href="https://www.livemint.com/companies/start-ups/onecode-raises-5-million-led-by-sequoia-s-surge-and-nexus-venture-partners-11626329270757.html">
                <img
                  src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fmint.410f3a1a.png&w=1080&q=75"
                  alt="image"
                />
              </a>
            </div>
          </div>
          <div className={styles.featuredLink}>
            <div className={styles.img1}>
              <a href="https://yourstory.com/2022/03/funding-alert-onecode-series-a-general-catalyst-financial-services">
                <img
                  src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FYourStory.1efabc81.png&w=1080&q=75"
                  alt="image"
                />
              </a>
            </div>
          </div>
          <div className={styles.featuredLink}>
            <div className={styles.img3}>
              <a href="https://www.business-standard.com/article/companies/onecode-raises-5-mn-led-by-sequoia-capital-s-surge-nexus-venture-partners-121071500470_1.html">
                <img
                  src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FBusinessStandard.047c592d.png&w=1080&q=75"
                  alt="image"
                />
              </a>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.meetInvestors}>
        <div className={styles.meetInvestorsTitle}>
          <p className={styles.pTitle}>Meet the Investors</p>
        </div>
        {/* <div className={styles.meetInvestorsCompany}>

        </div> */}
        <div className={styles.meetInvestorsPerson}>
          <div className={styles.d1}>
            <div className={styles.d11}>
              <img src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FInvCompany1.41d5c5bd.png&w=1200&q=75" alt="image"/>
            </div>
          </div>
          <div className={styles.d2}>
            <div className={styles.d11}>
              <img src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FInvCompany2.3f604866.png&w=640&q=75" alt="image"/>
          </div>
          </div>
          <div className={styles.d3}>
            <div className={styles.d11}>
              <img src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FInvCompany3.c16095cb.png&w=640&q=75" alt="image"/>
          </div>
          </div>
          <div className={styles.d4}>
            <div className={styles.d11}>
              <img src="https://zetapp.in/_next/image?url=%2F_next%2Fstatic%2Fmedia%2FInvCompany4.9acb56c2.png&w=640&q=75" alt="image"/>
          </div>
          </div>
        </div>
      </div>
      <div className={styles.invet}>
        <div className={styles.dd}></div>
        <div className={styles.dd}></div>
        <div className={styles.dd}></div>
        <div className={styles.dd}></div>
        <div className={styles.dd}></div>
        <div className={styles.dd}></div>
        <div className={styles.dd}></div>
        <div className={styles.dd}></div>
      </div>
    </>
  );
};

export default index;
